version: "3"
services:
  server:
    image: openjdk
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/voiceit_example?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=ALml%98213
      - MYSQL_DATABASE=voiceit_example
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=ALml%98213

networks:
  springmysql-net: